import Head from 'next/head'
import LottiePlayer from '../components/lottie'

export default function Home() {
  return (
    <div className="min-h-screen bg-black">
      <Head>
        <title>Baab World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LottiePlayer>

      </LottiePlayer>
      <div className="text-white text-8xl">Coming Soon...</div>
    </div>
  )
}
