import Head from 'next/head'

export default function Home() {
  return (
    <div className="bg-red-50">
      <Head>
        <title>Baab World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hi</div>
    </div>
  )
}
